### PR TITLE
ArrlDx - Quickly reports duplicate callsigns after starting contest

### LINKED ISSUE #437: ARRL DX Contest quickly reports duplicate contacts
### Description
The ARRL DX Contest only loads a small number of contacts and then quickly starts reporting duplicate contacts during a simulation run. 

### Steps To Reproduce
1. Select ARRL DX Contest
2. Start a simulation
3. Log a few contacts
4. Notice duplicates will start appearing after a few contacts are logged. 

#### Expected behavior
Duplicate contacts should be very rare during a simulation.  Usually 1000's of unique callsigns are loaded, so duplicates should be rare.

#### Actual Behavior
Only a few callsigns are loaded, so duplicates appear quickly. 

#### Reproduces how often
100%

### Version information
  - Morse Runner version: 1.85.3

### Additional context
Unfortunately this bug was introduced during a bug fix for version 1.85.3. This bug points out or weak testing strategy for a new release. Clearly, this contest was DOA and was obviously not tested. 

This bug was originally reported on groups.io [here](https://groups.io/g/MorseRunnerCE/message/194).

### Tasks

### PR DESCRIPTION
**Pull request by w7sst**
ArrlDx - Quickly reports duplicate callsigns after starting contest
- The FieldCnt was not computed correctly and caused most callsigns to be dropped. This resulted in DUPs being reported very soon in the contest.
- Introduce a new approach for parsing the call history files. This approach will eventually be moved in a common base class for reading call history files.
- FindIndex() is used to find each named column. An exception is thrown if a required field does not exist.
- GetValue() will load the value from each record. This technique does not require the field count to be used.
- fixes #437

### CODE REVIEW

File: ArrlDx.pas [hunk 1]
```diff
@@ -103,46 +123,36 @@ function TArrlDx.LoadCallHistory(const AUserCallsign: string) : boolean;
...
+          UserTextInx := FindIndex('UserText', False);
+
           continue;
         end;
-      if (tl.Count < FieldCount) then continue;
 
       if rec = nil then
         rec := TArrlDxCallRec.Create;
 
       // Using .Trim() to remove unexpected spaces in some records
```
Comment (swalberg) [inline ArrlDx.pas]: The `Trim()` now happens in `GetValue`, so I suggest the comment goes with it or is removed.

**Review by swalberg — APPROVED** [review]

File: ArrlDx.pas (hunk 1 above)
Comment (w7sst) [reply ArrlDx.pas]: Agreed. I removed the comment above the GetValue calls. Also updated a few comments and applied a couple of minor optimizations as suggested by AI. Thanks again.
